//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateProject.Database
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Clients
    {
        Entities entity = new Entities();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.ApartmentDemands = new HashSet<ApartmentDemands>();
            this.HouseDemands = new HashSet<HouseDemands>();
            this.LandDemands = new HashSet<LandDemands>();
        }

        public string ClientsName
        {
            get
            {
                if (entity.Clients.Any(x => x.Id == Id))
                {
                    var agents = entity.Clients.First(x => x.Id == Id);
                    return $"{agents.FirstName} {agents.MiddleName} {agents.LastName}";
                }
                else
                {
                    return "";
                }

            }
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApartmentDemands> ApartmentDemands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseDemands> HouseDemands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LandDemands> LandDemands { get; set; }
    }
}
